version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: football-mssql
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Banic-m3-uB.0"
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    networks:
      - football-network
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U SA -P "Banic-m3-uB.0" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: football-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:sqlserver://mssql:1433;databaseName=TicketSale;encrypt=true;trustServerCertificate=true
      SPRING_DATASOURCE_USERNAME: SA
      SPRING_DATASOURCE_PASSWORD: Banic-m3-uB.0
    depends_on:
      mssql:
        condition: service_healthy
    networks:
      - football-network

volumes:
  sqlserverdata:

networks:
  football-network:
    driver: bridge
